# Owner of the GitHub repository
owner: SRESchool

# Name of the GitHub repository
repo: All-Wizbrand-Websites-Uptime-Monitor

user-agent: pritesh-1904
skipReadme: true
skipDescription: true
skipTopics: true

# List of websites to monitor for uptime and SSL
sites:
  -name: airegistry.co
    url: https://airegistry.co
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: guestpostai.com
    url: https://guestpostai.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: wizbrand.com
    url: https://wizbrand.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: gurukulgalaxy.com
    url: https://gurukulgalaxy.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
  - name: cmsgalaxy.com
    url: https://cmsgalaxy.com
    method: GET
    followRedirects: true
    expectedStatus: 200
    ssl: true
    port: 80, 443
    check: "tcp-ping"
    ipv6: true

status-website:
  cname: null
  baseUrl: /All-Wizbrand-Websites-Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime/master/assets/logo.png
  name: All Wizbrand Websites Uptime Monitor
  introTitle: Wizbrand Websites Status
  introMessage: This page shows the uptime and SSL status of Wizbrand Websites.
  favicon: https://raw.githubusercontent.com/upptime/upptime/master/assets/favicon.ico
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Workflow schedule (every 5 minutes)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
  ssl: "*/5 * * * *"

# Committer configuration
committer:
  name: Pritesh
  email: contact@motoshare.in

# Email notification configuration
notifications:
  - type: email
    smtpTo: contact@motoshare.in
    smtpFrom: contact@motoshare.in
    smtpHost: smtp.gmail.com
    smtpPort: 587
    smtpUsername: contact@motoshare.in
    smtpPassword: kmxg nshc vsrf kxqj

# Assignees for issues
assignees:
  - pritesh-1904
